---
- hosts: sw_fde
  gather_facts: false
  connection: network_cli

  tasks:
    - name: desabilita interface com vlan wireless
      cisco.ios.ios_config:
        lines:
        - shutdown
        parents: switchport access vlan 171

